[development]
address = "localhost"
port = 8000
log = "normal"

[staging]
address = "localhost"
port = 8000
log = "normal"
template_dir = "/opt/storyestimates/templates"
swagger_dir = "/opt/storyestimates/swagger-ui"

[production]
address = "localhost"
port = 8000
log = "normal"
template_dir = "/opt/storyestimates/templates"
swagger_dir = "/opt/storyestimates/swagger-ui"
